
train_size: 0.9
val_size: 0.1
test_size: null
batch_size: 64
inference_batch_size: 32
ema_decay: 0.9999
grad_clip_val: 10

activation: silu
aggr: add
attn_activation: silu

gpus: 1
num_epochs: 500
test_interval: 100

model: eqgat

#ET
embedding_dimension: 256
num_heads: 8
rbf_type: expnorm
distance_influence: both
trainable_rbf: false
neighbor_embedding: true

#EQGAT
sdim: 256 #256
vdim: 64 #256
edim: 64 #256
use_norm: true
use_cross_product: false
use_bond_features: true
use_all_atom_features: false

#GENERAL MODEL SPECS
num_layers: 7
num_rbf: 32
use_local_edge_attr: false  
fully_connected_layer: true
fully_connected: false
skip_connect_context: False

cutoff_lower: 0.0
cutoff_upper: 7.0
cutoff_lower_global: 0.0
cutoff_upper_global: 15.0

#DATA
dataset: geom
dataset_arg: {}
dataset_root: /home/let55/workspace/projects/e3moldiffusion/geom/data

derivative: false
#Change for diffusion to VectorCategorical!
output_model: VectorCategorical

#DIFFUSION
num_atom_types: 5
atom_types: [1, 6, 7, 8, 9]
num_context_features: 0
properties_list: [] #[DIP, HLgap, eMBD, mPOL]
include_charges: false
remove_hs: false
condition_time: true
ode_regularization: 1.e-3
gradient_clipping: true
timesteps: 1000
norm_values: [1, 4, 10, 1]
n_stability_samples: 1000
noise_schedule: polynomial_2
noise_precision: 1.e-5
loss_type: l2

log_dir: logs
lr: 5.e-4
lr_factor: 0.5
lr_patience: 10
max_num_neighbors: 128
max_z: 100

weight_decay: 0.0

num_workers: 4
precision: 32