name: e3moldiffusion_new
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
  - pyg
  - nvidia
dependencies:
  - python=3.10.0
  - pytorch::pytorch=2.0.1
  - pyg::pyg=2.3.0
  - pyg::pytorch-scatter=2.1.1
  - pyg::pytorch-sparse=0.6.17
  - pyg::pytorch-cluster=1.6.1
  - conda-forge::rdkit=2023.03.2
  - conda-forge::pytorch-lightning=2.0.4
  - conda-forge::jupyter=1.0.0
  - conda-forge::openbabel=3.1.1
  - conda-forge::tensorboard=2.13.0
  - pip
  - notebook
  - matplotlib
  - pip:
      - ase
      - py3Dmol
      - nglview
      - rmsd
      - torch_ema