name: e3mol
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
  - pyg
  - nvidia
dependencies:
  - python=3.10.0
  - pip
  - notebook
  - matplotlib
  - pytorch::pytorch=2.0.1
  - pyg::pyg=2.3.0
  - pyg::pytorch-scatter
  - pyg::pytorch-sparse
  - pyg::pytorch-cluster
  - conda-forge::rdkit=2023.9.3
  - conda-forge::pytorch-lightning=2.0.6
  - xtb
  - conda-forge::jupyter
  - conda-forge::openbabel
  - conda-forge::prody
  - conda-forge::prolif
  - conda-forge::pypdb
  - conda-forge::datamol
  - conda-forge::py3dmol
  - anaconda::seaborn
  - anaconda::biopython=1.81
  - conda-forge::setuptools=65.6.3
  - pip:
      - ase
      - lmdb
      - nglview
      - rmsd
      - torch_ema
      - tensorboard
      - xtb
