name: e3moldiffusion
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
  - pyg
  - nvidia
dependencies:
  - python=3.10.0
  - pip
  - notebook
  - matplotlib
  - pytorch::pytorch=1.13.0
  - pyg::pyg=2.1.0
  - conda-forge::rdkit=2023.03.2
  - conda-forge::pytorch-lightning=1.7.4
  - conda-forge::jupyter
  - conda-forge::openbabel
  - pip:
      - ase
      - py3Dmol
      - lmdb
      - nglview
      - rmsd
      - torch_ema