name: e3moldiffusion
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
  - pyg
dependencies:
  - python=3.9.0
  - pip
  - notebook
  - matplotlib
  - rdkit=2021.09.4
  - pytorch::pytorch=1.11.0
  - pyg::pyg==2.0.4
  - conda-forge::pytorch-lightning=1.7.4
  - conda-forge::jupyter
  - conda-forge::xtb-python
  - pip:
      - ase
      - py3Dmol
      - lmdb
      - nglview