
load_ckpt: experiments/qm9/logs/x0/discrete_new_feats/run0/last.ckpt

batch_size: 200
inference_batch_size: 128
ema_decay: 0.999
grad_clip_val: 10
accum_batch: 1
gamma: 0.99

use_adaptive_loader: true
remove_hs: false

gpus: 1
num_epochs: 3000
test_interval: 10

#EQGAT
sdim: 256
vdim: 128
edim: 64
num_layers: 10
rbf_dim: 32
use_cross_product: false
local_edge_attrs: false
fully_connected: true
local_global_model: false
vector_aggr: mean
edge_mp: false

#DATA
dataset: qm9
dataset_root: experiments/qm9/data

# DIFFUSION
additional_feats: true
continuous: false
noise_scheduler: cosine
eps_min: 1.e-3
beta_min: 1.e-4
beta_max: 2.e-2
timesteps: 500
max_time: 06:00:00:00
use_loss_weighting: false

save_dir: experiments/qm9/logs/x0/discrete_new_feats
id: 1
lr: 4.e-4
lr_factor: 0.5
lr_patience: 10
max_num_neighbors: 128

weight_decay: 1.e-12

num_workers: 4
precision: 32