
#load_ckpt: /hpfs/userws/cremej01/workspace/logs/aqm_new/baseline_no_t_weighting/run0/last.ckpt
load_ckpt_from_pretrained: /hpfs/userws/cremej01/projects/logs/pubchem/x0_pretraining_0_snr_t_bs300/run0/last.ckpt

bond_prediction: false
seed: 42

# batch_size 40 without adaptive, and 200 with adaptive
batch_size: 32
inference_batch_size: 70
ema_decay: 0.999
grad_clip_val: 10
accum_batch: 1
gamma: 0.99

use_adaptive_loader: false
remove_hs: false

gpus: 1
num_epochs: 3000
test_interval: 20

#EQGAT
sdim: 256
vdim: 256
edim: 128
num_layers: 12
use_cross_product: false
edge_mp: false
fully_connected: true
local_global_model: false
vector_aggr: mean

#DATA
dataset: aqm
dataset_root: /hpfs/userws/cremej01/projects/data/aqm

# DIFFUSION
additional_feats: false
continuous: false
noise_scheduler: adaptive
eps_min: 1.e-3
beta_min: 1.e-4
beta_max: 2.e-2
timesteps: 500
max_time: 06:00:00:00
loss_weighting: uniform

#CONTEXT
context_mapping: false
num_context_features: 0
properties_list: [] #[DIP, HLgap, eMBD, mPOL]

#LOGGING
save_dir: /sharedhome/cremej01/workspace/logs/aqm/test_dip_hlgap
id: 0

#LEARNING
lr_scheduler: reduce_on_plateau
lr: 2.e-4
lr_min: 5.e-5 #used for cyclic scheduler
lr_step_size: 5.e-5 #used for cyclic scheduler
lr_factor: 0.75
lr_patience: 20
max_num_neighbors: 128
weight_decay: 1.e-12

num_workers: 4
precision: 32