
# load_ckpt: /sharedhome/cremej01/workspace/logs/qm9/x0_no_t_weighting/run0/last.ckpt
load_ckpt_from_pretrained: /sharedhome/cremej01/workspace/logs/pubchem/x0_pretraining_0_snr_t_weighting_bs400/run0/last.ckpt
# ckpt_bond_model: /hpfs/userws/cremej01/projects/logs/geom/bond_pred_seed1/run0/last.ckpt
bond_model_guidance: false
use_pos_norm: true

bond_prediction: false

seed: 42

# batch_size 40 without adaptive, and 200 with adaptive
batch_size: 32
inference_batch_size: 200
ema_decay: 0.999
grad_clip_val: 10
accum_batch: 1
gamma: 0.99

use_adaptive_loader: false
remove_hs: false

gpus: 4
num_epochs: 200
test_interval: 10

#EQGAT
sdim: 256
vdim: 256
edim: 128
num_layers: 12
use_cross_product: false
edge_mp: false
fully_connected: true
local_global_model: false
vector_aggr: mean

#DATA
dataset: qm9
dataset_root: /scratch1/cremej01/data/qm9
# dataset_root: /hpfs/userws/let55/projects/e3moldiffusion/experiments/geom/data

# DIFFUSION
additional_feats: false
continuous: false
noise_scheduler: adaptive
eps_min: 1.e-3
beta_min: 1.e-4
beta_max: 2.e-2
timesteps: 500
max_time: 06:00:00:00
loss_weighting: uniform

#LOGGING
save_dir: /hpfs/userws/cremej01/projects/logs/geom/pretrain_x0
id: 0

#LEARNING
lr_scheduler: reduce_on_plateau
lr: 2.e-4
lr_min: 5.e-5 #used for cyclic scheduler
lr_step_size: 5.e-5 #used for cyclic scheduler
lr_factor: 0.75
lr_patience: 20
max_num_neighbors: 128
weight_decay: 1.e-12

num_workers: 4
precision: 32